server:
  port : 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatApp?createDatabaseIfNotExist=true
    username: root
    password: Harshana123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false

